module.exports = {
  VALIDATION: 'VALIDATION_ERROR',
  AUTHENTICATION: 'AUTHENTICATION_ERROR',
  AUTHORIZATION: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND_ERROR',
  CONFLICT: 'CONFLICT_ERROR',
  SEQUELIZE: 'SEQUELIZE_ERROR',
  JWT: 'JWT_ERROR',
  INTERNAL: 'INTERNAL_ERROR',
};
